version: "3"

services:
  sobgestao:
    container_name: sobgestao
    build: ./
    working_dir: /var/www
    ports:
      - 8081:80
    volumes:
      - ./.docker/php.ini:/usr/local/etc/php/php.ini
      - ./.docker/logs:/var/log/apache2
      - ./:/var/www
      #- ~/.ssh/id_rsa:/user/.ssh/id_rsa
    networks:
      - localnet

networks:
  localnet:
    external: true
